### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by clpud** [codeif/Flask-WXApp#1]
When installing requirement `pycrypto`, get error message `Running setup.py install for pycrypto ... error`

**Comment by clpud** [comment]
solution in this post [python-3-install-pycrypto-windows](https://www.dariawan.com/tutorials/python/python-3-install-pycrypto-windows/) not working

**Comment by codeif** [comment]
@Sichen-Wang 是不是pycrypto的问题，falsk-wxapp的代码有需要改的地方吗？

**Comment by clpud** [comment]
> @Sichen-Wang 是不是pycrypto的问题，falsk-wxapp的代码有需要改的地方吗？

哈喽！是`pycrypto`的问题，但我还未使用过`flask-wxapp`，不知道代码有没有需要改的地方。
但对于`pycrypto`的问题是否将依赖改成`pycryptodome`就会ok呢😊

**Comment by codeif** [comment]
@Sichen-Wang 已更新
